[package]
name = "neural-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
rust-mnist = "0.2"
rand = "0.8"
rustacuda = "0.1"
nalgebra = "0.32.5"
